package compose

import (
	"fmt"
	"strings"

	"github.com/adnanex/dbctl/pkg/config"
)

// engineDefaults holds default Docker image and configuration per database engine.
type engineDefaults struct {
	Image       string
	EnvVars     map[string]string
	Volumes     []string
	DataDir     string
	Healthcheck string
}

var defaults = map[string]engineDefaults{
	"mysql": {
		Image: "mysql:8.0-debian",
		EnvVars: map[string]string{
			"MYSQL_ROOT_PASSWORD": "${MYSQL_ROOT_PASSWORD:-rootpassword}",
			// Without this, the image only creates 'root'@'localhost' —
			// connections via the published port (which MySQL sees coming
			// from the Docker bridge gateway, not literally "localhost")
			// get "Access denied".
			"MYSQL_ROOT_HOST": "%",
		},
		DataDir:     "/var/lib/mysql",
		Healthcheck: `["CMD", "mysqladmin", "ping", "-h", "localhost"]`,
	},
	"postgres": {
		Image: "postgres:16-alpine",
		EnvVars: map[string]string{
			"POSTGRES_PASSWORD": "${POSTGRES_PASSWORD:-rootpassword}",
		},
		DataDir:     "/var/lib/postgresql/data",
		Healthcheck: `["CMD-SHELL", "pg_isready -U postgres"]`,
	},
	"mongodb": {
		Image: "mongo:7",
		EnvVars: map[string]string{
			"MONGO_INITDB_ROOT_USERNAME": "root",
			"MONGO_INITDB_ROOT_PASSWORD": "${MONGO_INITDB_ROOT_PASSWORD:-rootpassword}",
		},
		DataDir:     "/data/db",
		Healthcheck: `["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]`,
	},
	"redis": {
		Image:       "redis:7-alpine",
		EnvVars:     map[string]string{},
		DataDir:     "/data",
		Healthcheck: `["CMD", "redis-cli", "ping"]`,
	},
}

// Generate creates a docker-compose.yml content string from a dbctl Config.
func Generate(cfg *config.Config) (string, error) {
	if len(cfg.Targets) == 0 {
		return "", fmt.Errorf("no targets defined in config")
	}

	var b strings.Builder

	b.WriteString("# Auto-generated by dbctl — regenerate with: dbctl up --generate-only\n")
	b.WriteString("# To use a custom compose file instead: dbctl up --compose ./your-file.yml\n\n")

	b.WriteString("services:\n")

	// Track volumes for declaration at the bottom
	volumeNames := make([]string, 0)

	// Track seen drivers to avoid duplicates
	seen := make(map[string]bool)

	for _, target := range cfg.Targets {
		driverKey := target.Driver
		if seen[driverKey] {
			continue
		}
		seen[driverKey] = true

		def, ok := defaults[driverKey]
		if !ok {
			return "", fmt.Errorf("unsupported driver for compose generation: %s", driverKey)
		}

		serviceName := fmt.Sprintf("dbctl-%s", driverKey)
		volumeName := fmt.Sprintf("dbctl-%s-data", driverKey)
		volumeNames = append(volumeNames, volumeName)

		// Determine image
		image := def.Image
		if target.Container != nil && target.Container.Image != "" {
			image = target.Container.Image
		}

		// Determine port
		port := target.Port

		b.WriteString(fmt.Sprintf("  %s:\n", serviceName))
		b.WriteString(fmt.Sprintf("    image: %s\n", image))
		b.WriteString(fmt.Sprintf("    container_name: %s\n", serviceName))
		b.WriteString("    restart: unless-stopped\n")

		// Ports
		b.WriteString("    ports:\n")
		b.WriteString(fmt.Sprintf("      - \"%d:%d\"\n", port, port))

		// Environment variables
		if len(def.EnvVars) > 0 {
			b.WriteString("    environment:\n")

			// Use admin password from config if available
			for key, val := range def.EnvVars {
				// Check if admin password should override default
				if target.Admin.Password != "" {
					if (driverKey == "mysql" && key == "MYSQL_ROOT_PASSWORD") ||
						(driverKey == "postgres" && key == "POSTGRES_PASSWORD") ||
						(driverKey == "mongodb" && key == "MONGO_INITDB_ROOT_PASSWORD") {
						val = target.Admin.Password
					}
				}
				if driverKey == "mongodb" && key == "MONGO_INITDB_ROOT_USERNAME" && target.Admin.Username != "" {
					val = target.Admin.Username
				}
				b.WriteString(fmt.Sprintf("      %s: \"%s\"\n", key, val))
			}
		}

		// Volumes
		b.WriteString("    volumes:\n")
		b.WriteString(fmt.Sprintf("      - %s:%s\n", volumeName, def.DataDir))

		// Custom volumes from container config
		if target.Container != nil && len(target.Container.Volumes) > 0 {
			for _, v := range target.Container.Volumes {
				b.WriteString(fmt.Sprintf("      - %s\n", v))
			}
		}

		// Healthcheck
		if def.Healthcheck != "" {
			b.WriteString("    healthcheck:\n")
			b.WriteString(fmt.Sprintf("      test: %s\n", def.Healthcheck))
			b.WriteString("      interval: 5s\n")
			b.WriteString("      timeout: 3s\n")
			b.WriteString("      retries: 10\n")
			b.WriteString("      start_period: 10s\n")
		}

		b.WriteString("\n")
	}

	// Volumes section
	if len(volumeNames) > 0 {
		b.WriteString("volumes:\n")
		for _, v := range volumeNames {
			b.WriteString(fmt.Sprintf("  %s:\n", v))
		}
	}

	return b.String(), nil
}
