package compose

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// StackEngine describes one service available in the full local database stack.
// Driver is the dbctl driver name used for provisioning (empty if the engine
// has no dbctl driver and is only managed as a container, e.g. redis).
type StackEngine struct {
	Driver      string
	Service     string
	Image       string
	Port        int
	Env         []string // ordered "KEY=value" pairs, value may contain ${VAR:-default}
	Command     []string
	DataPath    string
	Healthcheck []string
}

var stackEngines = map[string]StackEngine{
	"mysql": {
		Driver: "mysql", Service: "mysql", Image: "mysql:8.0-debian", Port: 3306,
		Env:         []string{"MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-rootpassword}"},
		DataPath:    "/var/lib/mysql",
		Healthcheck: []string{"CMD", "mysqladmin", "ping", "-h", "localhost"},
	},
	"postgres": {
		Driver: "postgres", Service: "postgres", Image: "postgres:16-alpine", Port: 5432,
		Env:         []string{"POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-rootpassword}"},
		DataPath:    "/var/lib/postgresql/data",
		Healthcheck: []string{"CMD-SHELL", "pg_isready -U postgres"},
	},
	"mongo": {
		Driver: "mongodb", Service: "mongo", Image: "mongo:7", Port: 27017,
		Env: []string{
			"MONGO_INITDB_ROOT_USERNAME=root",
			"MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:-rootpassword}",
		},
		DataPath:    "/data/db",
		Healthcheck: []string{"CMD", "mongosh", "--eval", "db.adminCommand('ping')"},
	},
	"redis": {
		Service: "redis", Image: "redis:7-alpine", Port: 6379,
		DataPath:    "/data",
		Healthcheck: []string{"CMD", "redis-cli", "ping"},
	},
	"rabbitmq": {
		Service: "rabbitmq", Image: "rabbitmq:3-management-alpine", Port: 5672,
		Env: []string{
			"RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER:-guest}",
			"RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS:-guest}",
		},
		DataPath:    "/var/lib/rabbitmq",
		Healthcheck: []string{"CMD", "rabbitmq-diagnostics", "-q", "ping"},
	},
	"kafka": {
		Service: "kafka", Image: "bitnami/kafka:3.7", Port: 9092,
		Env: []string{
			"KAFKA_CFG_NODE_ID=0",
			"KAFKA_CFG_PROCESS_ROLES=controller,broker",
			"KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093",
			"KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092",
			"KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093",
			"KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER",
			"ALLOW_PLAINTEXT_LISTENER=yes",
		},
		DataPath:    "/bitnami/kafka",
		Healthcheck: []string{"CMD-SHELL", "kafka-topics.sh --bootstrap-server localhost:9092 --list"},
	},
	"nats": {
		Service: "nats", Image: "nats:2-alpine", Port: 4222,
		Command:     []string{"-js", "-m", "8222"},
		DataPath:    "/data",
		Healthcheck: []string{"CMD-SHELL", "nc -z localhost 4222 || exit 1"},
	},
	"typesense": {
		Service: "typesense", Image: "typesense/typesense:27.1", Port: 8108,
		Command:     []string{"--data-dir", "/data", "--api-key=${TYPESENSE_API_KEY:-xyz}"},
		DataPath:    "/data",
		Healthcheck: []string{"CMD-SHELL", "curl -fs http://localhost:8108/health || exit 1"},
	},
}

// StackEngineKeys returns the supported stack engine keys, sorted alphabetically.
func StackEngineKeys() []string {
	keys := make([]string, 0, len(stackEngines))
	for k := range stackEngines {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// ProjectName derives a Docker Compose project name for a stack directory from
// its absolute path, so two stacks that happen to share a directory basename
// (e.g. two unrelated "dbs" folders) never collide under Compose's default
// "project name = directory basename" behavior, which otherwise causes `docker
// compose down` in one to stop/remove containers belonging to the other.
func ProjectName(dir string) string {
	abs, err := filepath.Abs(dir)
	if err != nil {
		abs = dir
	}
	sum := sha256.Sum256([]byte(abs))
	return "dbctl-" + hex.EncodeToString(sum[:])[:12]
}

// GenerateStack builds docker-compose.yml content for the requested engines.
// An empty/nil engines slice generates the full default stack. projectName, if
// non-empty, is written as the top-level Compose "name" to pin the project
// identity to this specific stack directory (see ProjectName).
func GenerateStack(engines []string, projectName string) (string, error) {
	if len(engines) == 0 {
		engines = StackEngineKeys()
	}

	var b strings.Builder
	b.WriteString("# Auto-generated by dbctl — regenerate with: dbctl init stack --force\n")
	b.WriteString("# Discovered automatically via DBCTL_COMPOSE_FILE / DBCTL_STACK, or ~/.dbctl/dbs, ./dbs\n\n")
	if projectName != "" {
		b.WriteString(fmt.Sprintf("name: %s\n\n", projectName))
	}
	b.WriteString("services:\n")

	volumeNames := make([]string, 0, len(engines))
	seen := make(map[string]bool)

	for _, key := range engines {
		key = strings.ToLower(strings.TrimSpace(key))
		if seen[key] {
			continue
		}
		seen[key] = true

		eng, ok := stackEngines[key]
		if !ok {
			return "", fmt.Errorf("unknown stack engine %q (available: %s)", key, strings.Join(StackEngineKeys(), ", "))
		}

		volumeName := fmt.Sprintf("dbctl-%s-data", eng.Service)
		volumeNames = append(volumeNames, volumeName)

		b.WriteString(fmt.Sprintf("  %s:\n", eng.Service))
		b.WriteString(fmt.Sprintf("    image: %s\n", eng.Image))
		b.WriteString(fmt.Sprintf("    container_name: dbctl-%s\n", eng.Service))
		b.WriteString("    restart: unless-stopped\n")

		b.WriteString("    ports:\n")
		b.WriteString(fmt.Sprintf("      - \"%d:%d\"\n", eng.Port, eng.Port))

		if len(eng.Command) > 0 {
			b.WriteString("    command:\n")
			for _, c := range eng.Command {
				b.WriteString(fmt.Sprintf("      - %q\n", c))
			}
		}

		if len(eng.Env) > 0 {
			b.WriteString("    environment:\n")
			for _, kv := range eng.Env {
				parts := strings.SplitN(kv, "=", 2)
				b.WriteString(fmt.Sprintf("      %s: \"%s\"\n", parts[0], parts[1]))
			}
		}

		if eng.DataPath != "" {
			b.WriteString("    volumes:\n")
			b.WriteString(fmt.Sprintf("      - %s:%s\n", volumeName, eng.DataPath))
		}

		if len(eng.Healthcheck) > 0 {
			b.WriteString("    healthcheck:\n")
			b.WriteString("      test:\n")
			for _, part := range eng.Healthcheck {
				b.WriteString(fmt.Sprintf("        - %q\n", part))
			}
			b.WriteString("      interval: 5s\n")
			b.WriteString("      timeout: 3s\n")
			b.WriteString("      retries: 10\n")
			b.WriteString("      start_period: 10s\n")
		}

		b.WriteString("\n")
	}

	if len(volumeNames) > 0 {
		b.WriteString("volumes:\n")
		for _, v := range volumeNames {
			b.WriteString(fmt.Sprintf("  %s:\n", v))
		}
	}

	return b.String(), nil
}

// GenerateStackConfig builds a dbctl config.yaml (defaults-style) that wires
// the driver-backed engines (mysql, postgres, mongo) in the given stack to the
// generated compose file at composeFilePath.
func GenerateStackConfig(engines []string, composeFilePath string) string {
	if len(engines) == 0 {
		engines = StackEngineKeys()
	}

	var b strings.Builder
	b.WriteString("# Auto-generated by dbctl — points dbctl at the generated stack.\n")
	b.WriteString("# Default locations: ~/.dbctl/config.yaml or ~/.config/dbctl/config.yaml\n\n")
	b.WriteString("defaults:\n")

	wrote := false
	for _, key := range engines {
		key = strings.ToLower(strings.TrimSpace(key))
		eng, ok := stackEngines[key]
		if !ok || eng.Driver == "" {
			continue
		}
		wrote = true

		b.WriteString(fmt.Sprintf("  %s:\n", eng.Driver))
		b.WriteString("    container:\n")
		b.WriteString(fmt.Sprintf("      compose_file: \"%s\"\n", composeFilePath))
		b.WriteString(fmt.Sprintf("      service: \"%s\"\n", eng.Service))
	}

	if !wrote {
		b.WriteString("  {} # no provisionable engines selected (redis/rabbitmq/kafka/nats/typesense have no dbctl driver)\n")
	}

	return b.String()
}

// WriteStack writes docker-compose.yml for the given engines into dir.
// Returns the absolute path of the written file.
func WriteStack(dir string, engines []string, force bool) (string, error) {
	content, err := GenerateStack(engines, ProjectName(dir))
	if err != nil {
		return "", err
	}

	if err := os.MkdirAll(dir, 0755); err != nil {
		return "", fmt.Errorf("failed to create directory %s: %w", dir, err)
	}

	path := filepath.Join(dir, "docker-compose.yml")
	if !force {
		if _, err := os.Stat(path); err == nil {
			return "", fmt.Errorf("file %s already exists (use --force to overwrite)", path)
		}
	}

	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		return "", fmt.Errorf("failed to write %s: %w", path, err)
	}

	abs, err := filepath.Abs(path)
	if err != nil {
		return path, nil
	}
	return abs, nil
}

// WriteStackConfig writes a config.yaml at configPath referencing composeFilePath for the given engines.
func WriteStackConfig(configPath string, engines []string, composeFilePath string, force bool) error {
	if !force {
		if _, err := os.Stat(configPath); err == nil {
			return fmt.Errorf("file %s already exists (use --force to overwrite)", configPath)
		}
	}

	dir := filepath.Dir(configPath)
	if dir != "" && dir != "." {
		if err := os.MkdirAll(dir, 0755); err != nil {
			return fmt.Errorf("failed to create directory %s: %w", dir, err)
		}
	}

	content := GenerateStackConfig(engines, composeFilePath)
	if err := os.WriteFile(configPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write %s: %w", configPath, err)
	}

	return nil
}
