package compose

import (
	_ "embed"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

//go:embed templates/stack/docker-compose.yml
var stackTemplate string

//go:embed templates/stack/engines.yaml
var stackEngineDrivers []byte

// engineDrivers maps a stack service/engine key to its dbctl driver name, as
// declared in templates/stack/engines.yaml. Engines with no dbctl driver
// (e.g. redis, rabbitmq, kafka, nats, typesense) are simply absent.
func engineDrivers() map[string]string {
	var m map[string]string
	_ = yaml.Unmarshal(stackEngineDrivers, &m)
	return m
}

// servicesNode returns the "services" mapping node of the embedded stack template.
func servicesNode() (*yaml.Node, error) {
	var root yaml.Node
	if err := yaml.Unmarshal([]byte(stackTemplate), &root); err != nil {
		return nil, fmt.Errorf("failed to parse stack template: %w", err)
	}
	if len(root.Content) == 0 {
		return nil, fmt.Errorf("stack template is empty")
	}
	return findChild(root.Content[0], "services")
}

// findChild returns the value node for key in a YAML mapping node.
func findChild(mapping *yaml.Node, key string) (*yaml.Node, error) {
	for i := 0; i+1 < len(mapping.Content); i += 2 {
		if mapping.Content[i].Value == key {
			return mapping.Content[i+1], nil
		}
	}
	return nil, fmt.Errorf("key %q not found", key)
}

// StackEngineKeys returns the supported stack engine keys, sorted alphabetically,
// as declared by the embedded stack template's services.
func StackEngineKeys() []string {
	services, err := servicesNode()
	if err != nil {
		return nil
	}
	keys := make([]string, 0, len(services.Content)/2)
	for i := 0; i+1 < len(services.Content); i += 2 {
		keys = append(keys, services.Content[i].Value)
	}
	sort.Strings(keys)
	return keys
}

// GenerateStack builds docker-compose.yml content for the requested engines by
// filtering the embedded stack template down to just those services (and their
// matching named volumes). An empty/nil engines slice generates the full stack.
// projectName, if non-empty, is written as the top-level Compose "name" to pin
// the project identity to this specific stack directory (see ProjectName).
func GenerateStack(engines []string, projectName string) (string, error) {
	allKeys := StackEngineKeys()
	if len(engines) == 0 {
		engines = allKeys
	}

	var root yaml.Node
	if err := yaml.Unmarshal([]byte(stackTemplate), &root); err != nil {
		return "", fmt.Errorf("failed to parse stack template: %w", err)
	}
	services, err := findChild(root.Content[0], "services")
	if err != nil {
		return "", fmt.Errorf("stack template has no services section")
	}
	volumes, _ := findChild(root.Content[0], "volumes") // optional
	networks, _ := findChild(root.Content[0], "networks") // optional, shared by all services

	selected := make(map[string]bool, len(engines))
	for _, e := range engines {
		key := strings.ToLower(strings.TrimSpace(e))
		if _, err := findChild(services, key); err != nil {
			return "", fmt.Errorf("unknown stack engine %q (available: %s)", key, strings.Join(allKeys, ", "))
		}
		selected[key] = true
	}

	filteredServices := &yaml.Node{Kind: yaml.MappingNode, Tag: "!!map"}
	for i := 0; i+1 < len(services.Content); i += 2 {
		key := services.Content[i].Value
		if selected[key] {
			filteredServices.Content = append(filteredServices.Content, services.Content[i], services.Content[i+1])
		}
	}

	out := &yaml.Node{Kind: yaml.MappingNode, Tag: "!!map"}
	appendKV(out, "services", filteredServices)

	if networks != nil {
		// All services share the same network(s), so pass the section through as-is.
		appendKV(out, "networks", networks)
	}

	if volumes != nil {
		filteredVolumes := &yaml.Node{Kind: yaml.MappingNode, Tag: "!!map"}
		for i := 0; i+1 < len(volumes.Content); i += 2 {
			volName := volumes.Content[i].Value
			for svc := range selected {
				if volName == fmt.Sprintf("dbctl-%s-data", svc) {
					filteredVolumes.Content = append(filteredVolumes.Content, volumes.Content[i], volumes.Content[i+1])
					break
				}
			}
		}
		if len(filteredVolumes.Content) > 0 {
			appendKV(out, "volumes", filteredVolumes)
		}
	}

	body, err := yaml.Marshal(out)
	if err != nil {
		return "", fmt.Errorf("failed to render stack compose: %w", err)
	}

	var b strings.Builder
	b.WriteString("# Auto-generated by dbctl — regenerate with: dbctl init stack --force\n")
	b.WriteString("# Discovered automatically via DBCTL_COMPOSE_FILE / DBCTL_STACK, or ~/.dbctl/dbs, ./dbs\n\n")
	if projectName != "" {
		b.WriteString(fmt.Sprintf("name: %s\n\n", projectName))
	}
	b.Write(body)

	return b.String(), nil
}

func appendKV(mapping *yaml.Node, key string, value *yaml.Node) {
	mapping.Content = append(mapping.Content, &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: key}, value)
}

// ProjectName derives a Docker Compose project name for a stack directory from
// its absolute path, so two stacks that happen to share a directory basename
// (e.g. two unrelated "dbs" folders) never collide under Compose's default
// "project name = directory basename" behavior, which otherwise causes `docker
// compose down` in one to stop/remove containers belonging to the other.
func ProjectName(dir string) string {
	abs, err := filepath.Abs(dir)
	if err != nil {
		abs = dir
	}
	sum := sha256.Sum256([]byte(abs))
	return "dbctl-" + hex.EncodeToString(sum[:])[:12]
}

// GenerateStackConfig builds a dbctl config.yaml (defaults-style) that wires
// the driver-backed engines (per templates/stack/engines.yaml) in the given
// stack to the generated compose file at composeFilePath.
func GenerateStackConfig(engines []string, composeFilePath string) string {
	if len(engines) == 0 {
		engines = StackEngineKeys()
	}
	drivers := engineDrivers()

	var b strings.Builder
	b.WriteString("# Auto-generated by dbctl — points dbctl at the generated stack.\n")
	b.WriteString("# Default locations: ~/.dbctl/config.yaml or ~/.config/dbctl/config.yaml\n\n")
	b.WriteString("defaults:\n")

	wrote := false
	for _, key := range engines {
		key = strings.ToLower(strings.TrimSpace(key))
		driver, ok := drivers[key]
		if !ok || driver == "" {
			continue
		}
		wrote = true

		b.WriteString(fmt.Sprintf("  %s:\n", driver))
		b.WriteString("    container:\n")
		b.WriteString(fmt.Sprintf("      compose_file: \"%s\"\n", composeFilePath))
		b.WriteString(fmt.Sprintf("      service: \"%s\"\n", key))
	}

	if !wrote {
		b.WriteString("  {} # no provisionable engines selected (some engines have no dbctl driver)\n")
	}

	return b.String()
}

// WriteStack writes docker-compose.yml for the given engines into dir.
// Returns the absolute path of the written file.
func WriteStack(dir string, engines []string, force bool) (string, error) {
	content, err := GenerateStack(engines, ProjectName(dir))
	if err != nil {
		return "", err
	}

	if err := os.MkdirAll(dir, 0755); err != nil {
		return "", fmt.Errorf("failed to create directory %s: %w", dir, err)
	}

	path := filepath.Join(dir, "docker-compose.yml")
	if !force {
		if _, err := os.Stat(path); err == nil {
			return "", fmt.Errorf("file %s already exists (use --force to overwrite)", path)
		}
	}

	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		return "", fmt.Errorf("failed to write %s: %w", path, err)
	}

	abs, err := filepath.Abs(path)
	if err != nil {
		return path, nil
	}
	return abs, nil
}

// WriteStackConfig writes a config.yaml at configPath referencing composeFilePath for the given engines.
func WriteStackConfig(configPath string, engines []string, composeFilePath string, force bool) error {
	if !force {
		if _, err := os.Stat(configPath); err == nil {
			return fmt.Errorf("file %s already exists (use --force to overwrite)", configPath)
		}
	}

	dir := filepath.Dir(configPath)
	if dir != "" && dir != "." {
		if err := os.MkdirAll(dir, 0755); err != nil {
			return fmt.Errorf("failed to create directory %s: %w", dir, err)
		}
	}

	content := GenerateStackConfig(engines, composeFilePath)
	if err := os.WriteFile(configPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write %s: %w", configPath, err)
	}

	return nil
}
